In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("aug_train.csv")

In [6]:
df.shape

(19158, 14)

In [8]:
df.sample(5)   # random rows are print

,enrollee_id,city,city_development_index,gender,relevent_experience,enrolled_university,education_level,major_discipline,experience,company_size,company_type,last_new_job,training_hours,target
2170,3538,city_103,0.920,Male,Has relevent experience,no_enrollment,Graduate,Humanities,>20,10000+,Pvt Ltd,>4,86,0.0
4458,18608,city_21,0.624,Male,Has relevent experience,no_enrollment,Graduate,STEM,5,100-500,Pvt Ltd,1,130,1.0
14826,12356,city_143,0.740,Male,Has relevent experience,no_enrollment,Graduate,STEM,11,50-99,Pvt Ltd,never,22,0.0
4212,1686,city_103,0.920,Male,No relevent experience,Full time course,Graduate,STEM,2,NaN,NaN,never,42,1.0
1381,28081,city_160,0.920,Male,No relevent experience,Full time course,Graduate,STEM,>20,100-500,Pvt Ltd,1,4,0.0

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 19158 entries, 0 to 19157
Data columns (total 14 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   enrollee_id             19158 non-null  int64
 1   city                    19158 non-null  object
 2   city_development_index  19158 non-null  float64
 3   gender                  14650 non-null  object
 4   relevent_experience     19158 non-null  object
 5   enrolled_university     18772 non-null  object
 6   education_level         18698 non-null  object
 7   major_discipline        16345 non-null  object
 8   experience              19093 non-null  object
 9   company_size            13220 non-null  object
 10  company_type            13018 non-null  object
 11  last_new_job            18735 non-null  object
 12  training_hours          19158 non-null  int64
 13  target                  19158 non-null  float64
dtypes: float64(2), int64(2), object(10)
memory usage: 2.0+ MB

In [11]:
df.isnull().sum()

enrollee_id                  0
city                         0
city_development_index       0
gender                    4508
relevent_experience          0
enrolled_university        386
education_level            460
major_discipline          2813
experience                  65
company_size              5938
company_type              6140
last_new_job               423
training_hours               0
target                       0
dtype: int64

In [13]:
df.describe()

        enrollee_id  city_development_index  training_hours        target
count  19158.000000            19158.000000    19158.000000  19158.000000
mean   16875.358179                0.828848       65.366896      0.249348
std     9616.292592                0.123362       60.058462      0.432647
min        1.000000                0.448000        1.000000      0.000000
25%     8554.250000                0.740000       23.000000      0.000000
50%    16982.500000                0.903000       47.000000      0.000000
75%    25169.750000                0.920000       88.000000      0.000000
max    33380.000000                0.949000      336.000000      1.000000

In [16]:
df.duplicated().sum()

np.int64(0)

In [20]:
df.corr()['relevent_experience']

ValueError: could not convert string to float: 'city_103'

In [1]:
!git --version

git version 2.51.0.windows.1

In [4]:
!git clone https://github.com/mayankgupta6310/Machine-Learning.git

Cloning into 'Machine-Learning'...