In [1]:
import pandas as pd

In [2]:
pd.read_json("train.json")

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [3]:
!pip install mysql.connector

Collecting mysql.connector
  Downloading mysql-connector-2.2.9.tar.gz (11.9 MB)
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
      --------------------------------------- 0.3/11.9 MB ? eta -:--:--
     - ------------------------------------- 0.5/11.9 MB 285.3 kB/s eta 0:00:40
     - ------------------------------------- 0.5/11.9 MB 285.3 kB/s eta 0:00:40
     - ------------------------------------- 0.5/11.9 MB 285.3 kB/s eta 0:00:40
     - ------------------------------------- 0.5/11.9 MB 285.3 kB/s eta 0:00:40
     -- ------------------------------------ 0.8/11.9 MB 306.9 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/11.9 MB 306.9 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/11.9 MB 306.9 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/11.9 MB 306.9 kB/s eta 0:00:37
     -- ------------------------------------ 0.8/11.9 MB 306.9 kB/s eta 0:00:37
     --- ----------------------------------- 1.0/11.9 MB 288.4 kB/s eta 0:00:38
     --- ----------------------------------- 1.0/11.9 MB 288.4 kB/s eta 0:00:38
     --- ----------------------------------- 1.0/11.9 MB 288.4 kB/s eta 0:00:38
     --- ----------------------------------- 1.0/11.9 MB 288.4 kB/s eta 0:00:38
     --- ----------------------------------- 1.0/11.9 MB 288.4 kB/s eta 0:00:38
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ---- ---------------------------------- 1.3/11.9 MB 272.0 kB/s eta 0:00:39
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ----- --------------------------------- 1.6/11.9 MB 188.6 kB/s eta 0:00:55
     ------ -------------------------------- 1.8/11.9 MB 181.7 kB/s eta 0:00:56
     ------ -------------------------------- 1.8/11.9 MB 181.7 kB/s eta 0:00:56
     ------ -------------------------------- 1.8/11.9 MB 181.7 kB/s eta 0:00:56
     ------ -------------------------------- 1.8/11.9 MB 181.7 kB/s eta 0:00:56
     ------ -------------------------------- 1.8/11.9 MB 181.7 kB/s eta 0:00:56
     ------ -------------------------------- 2.1/11.9 MB 188.1 kB/s eta 0:00:52
     ------ -------------------------------- 2.1/11.9 MB 188.1 kB/s eta 0:00:52
     ------ -------------------------------- 2.1/11.9 MB 188.1 kB/s eta 0:00:52
     ------ -------------------------------- 2.1/11.9 MB 188.1 kB/s eta 0:00:52
     ------ -------------------------------- 2.1/11.9 MB 188.1 kB/s eta 0:00:52
     ------- ------------------------------- 2.4/11.9 MB 195.1 kB/s eta 0:00:49
     ------- ------------------------------- 2.4/11.9 MB 195.1 kB/s eta 0:00:49
     ------- ------------------------------- 2.4/11.9 MB 195.1 kB/s eta 0:00:49
     ------- ------------------------------- 2.4/11.9 MB 195.1 kB/s eta 0:00:49
     ------- ------------------------------- 2.4/11.9 MB 195.1 kB/s eta 0:00:49
     ------- ------------------------------- 2.4/11.9 MB 195.1 kB/s eta 0:00:49
     -------- ------------------------------ 2.6/11.9 MB 196.3 kB/s eta 0:00:48
     -------- ------------------------------ 2.6/11.9 MB 196.3 kB/s eta 0:00:48
     -------- ------------------------------ 2.6/11.9 MB 196.3 kB/s eta 0:00:48
     -------- ------------------------------ 2.6/11.9 MB 196.3 kB/s eta 0:00:48
     -------- ------------------------------ 2.6/11.9 MB 196.3 kB/s eta 0:00:48
     -------- ------------------------------ 2.6/11.9 MB 196.3 kB/s eta 0:00:48
     --------- ----------------------------- 2.9/11.9 MB 197.8 kB/s eta 0:00:46
     --------- ----------------------------- 2.9/11.9 MB 197.8 kB/s eta 0:00:46
     --------- ----------------------------- 2.9/11.9 MB 197.8 kB/s eta 0:00:46
     --------- ----------------------------- 2.9/11.9 MB 197.8 kB/s eta 0:00:46
     ---------- ---------------------------- 3.1/11.9 MB 203.4 kB/s eta 0:00:43
     ---------- ---------------------------- 3.1/11.9 MB 203.4 kB/s eta 0:00:43
     ---------- ---------------------------- 3.1/11.9 MB 203.4 kB/s eta 0:00:43
     ---------- ---------------------------- 3.1/11.9 MB 203.4 kB/s eta 0:00:43
     ---------- ---------------------------- 3.1/11.9 MB 203.4 kB/s eta 0:00:43
     ----------- --------------------------- 3.4/11.9 MB 206.8 kB/s eta 0:00:41
     ----------- --------------------------- 3.4/11.9 MB 206.8 kB/s eta 0:00:41
     ----------- --------------------------- 3.4/11.9 MB 206.8 kB/s eta 0:00:41
     ----------- --------------------------- 3.4/11.9 MB 206.8 kB/s eta 0:00:41
     ------------ -------------------------- 3.7/11.9 MB 214.5 kB/s eta 0:00:39
     ------------ -------------------------- 3.7/11.9 MB 214.5 kB/s eta 0:00:39
     ------------ -------------------------- 3.7/11.9 MB 214.5 kB/s eta 0:00:39
     ------------ -------------------------- 3.9/11.9 MB 220.5 kB/s eta 0:00:36
     ------------ -------------------------- 3.9/11.9 MB 220.5 kB/s eta 0:00:36
     ------------ -------------------------- 3.9/11.9 MB 220.5 kB/s eta 0:00:36
     ------------- ------------------------- 4.2/11.9 MB 227.0 kB/s eta 0:00:34
     ------------- ------------------------- 4.2/11.9 MB 227.0 kB/s eta 0:00:34
     ------------- ------------------------- 4.2/11.9 MB 227.0 kB/s eta 0:00:34
     -------------- ------------------------ 4.5/11.9 MB 235.4 kB/s eta 0:00:32
     -------------- ------------------------ 4.5/11.9 MB 235.4 kB/s eta 0:00:32
     --------------- ----------------------- 4.7/11.9 MB 243.5 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 243.5 kB/s eta 0:00:30
     --------------- ----------------------- 4.7/11.9 MB 243.5 kB/s eta 0:00:30
     ---------------- ---------------------- 5.0/11.9 MB 249.4 kB/s eta 0:00:28
     ---------------- ---------------------- 5.0/11.9 MB 249.4 kB/s eta 0:00:28
     ---------------- ---------------------- 5.0/11.9 MB 249.4 kB/s eta 0:00:28
     ----------------- --------------------- 5.2/11.9 MB 255.0 kB/s eta 0:00:26
     ----------------- --------------------- 5.2/11.9 MB 255.0 kB/s eta 0:00:26
     ----------------- --------------------- 5.2/11.9 MB 255.0 kB/s eta 0:00:26
     ------------------ -------------------- 5.5/11.9 MB 260.6 kB/s eta 0:00:25
     ------------------ -------------------- 5.5/11.9 MB 260.6 kB/s eta 0:00:25
     ------------------ -------------------- 5.8/11.9 MB 267.0 kB/s eta 0:00:23
     ------------------ -------------------- 5.8/11.9 MB 267.0 kB/s eta 0:00:23
     ------------------ -------------------- 5.8/11.9 MB 267.0 kB/s eta 0:00:23
     ------------------- ------------------- 6.0/11.9 MB 272.9 kB/s eta 0:00:22
     ------------------- ------------------- 6.0/11.9 MB 272.9 kB/s eta 0:00:22
     ------------------- ------------------- 6.0/11.9 MB 272.9 kB/s eta 0:00:22
     ------------------- ------------------- 6.0/11.9 MB 272.9 kB/s eta 0:00:22
     -------------------- ------------------ 6.3/11.9 MB 274.1 kB/s eta 0:00:21
     -------------------- ------------------ 6.3/11.9 MB 274.1 kB/s eta 0:00:21
     --------------------- ----------------- 6.6/11.9 MB 279.3 kB/s eta 0:00:19
     --------------------- ----------------- 6.6/11.9 MB 279.3 kB/s eta 0:00:19
     --------------------- ----------------- 6.6/11.9 MB 279.3 kB/s eta 0:00:19
     --------------------- ----------------- 6.6/11.9 MB 279.3 kB/s eta 0:00:19
     ---------------------- ---------------- 6.8/11.9 MB 280.1 kB/s eta 0:00:18
     ---------------------- ---------------- 6.8/11.9 MB 280.1 kB/s eta 0:00:18
     ---------------------- ---------------- 6.8/11.9 MB 280.1 kB/s eta 0:00:18
     ---------------------- ---------------- 6.8/11.9 MB 280.1 kB/s eta 0:00:18
     ---------------------- ---------------- 6.8/11.9 MB 280.1 kB/s eta 0:00:18
     ---------------------- ---------------- 6.8/11.9 MB 280.1 kB/s eta 0:00:18
     ---------------------- ---------------- 6.8/11.9 MB 280.1 kB/s eta 0:00:18
     ----------------------- --------------- 7.1/11.9 MB 275.8 kB/s eta 0:00:18
     ----------------------- --------------- 7.1/11.9 MB 275.8 kB/s eta 0:00:18
     ------------------------ -------------- 7.3/11.9 MB 280.3 kB/s eta 0:00:17
     ------------------------ -------------- 7.3/11.9 MB 280.3 kB/s eta 0:00:17
     ------------------------ -------------- 7.3/11.9 MB 280.3 kB/s eta 0:00:17
     ------------------------- ------------- 7.6/11.9 MB 283.8 kB/s eta 0:00:15
     ------------------------- ------------- 7.6/11.9 MB 283.8 kB/s eta 0:00:15
     ------------------------- ------------- 7.6/11.9 MB 283.8 kB/s eta 0:00:15
     ------------------------- ------------- 7.9/11.9 MB 288.0 kB/s eta 0:00:14
     ------------------------- ------------- 7.9/11.9 MB 288.0 kB/s eta 0:00:14
     ------------------------- ------------- 7.9/11.9 MB 288.0 kB/s eta 0:00:14
     -------------------------- ------------ 8.1/11.9 MB 291.3 kB/s eta 0:00:13
     -------------------------- ------------ 8.1/11.9 MB 291.3 kB/s eta 0:00:13
     -------------------------- ------------ 8.1/11.9 MB 291.3 kB/s eta 0:00:13
     --------------------------- ----------- 8.4/11.9 MB 294.5 kB/s eta 0:00:12
     --------------------------- ----------- 8.4/11.9 MB 294.5 kB/s eta 0:00:12
     --------------------------- ----------- 8.4/11.9 MB 294.5 kB/s eta 0:00:12
     ---------------------------- ---------- 8.7/11.9 MB 296.0 kB/s eta 0:00:11
     ---------------------------- ---------- 8.7/11.9 MB 296.0 kB/s eta 0:00:11
     ---------------------------- ---------- 8.7/11.9 MB 296.0 kB/s eta 0:00:11
     ----------------------------- --------- 8.9/11.9 MB 299.4 kB/s eta 0:00:10
     ----------------------------- --------- 8.9/11.9 MB 299.4 kB/s eta 0:00:10
     ----------------------------- --------- 8.9/11.9 MB 299.4 kB/s eta 0:00:10
     ------------------------------ -------- 9.2/11.9 MB 301.0 kB/s eta 0:00:09
     ------------------------------ -------- 9.2/11.9 MB 301.0 kB/s eta 0:00:09
     ------------------------------ -------- 9.2/11.9 MB 301.0 kB/s eta 0:00:09
     ------------------------------ -------- 9.2/11.9 MB 301.0 kB/s eta 0:00:09
     ------------------------------ -------- 9.2/11.9 MB 301.0 kB/s eta 0:00:09
     ------------------------------ -------- 9.2/11.9 MB 301.0 kB/s eta 0:00:09
     ------------------------------- ------- 9.4/11.9 MB 297.6 kB/s eta 0:00:09
     ------------------------------- ------- 9.4/11.9 MB 297.6 kB/s eta 0:00:09
     ------------------------------- ------- 9.4/11.9 MB 297.6 kB/s eta 0:00:09
     ------------------------------- ------- 9.7/11.9 MB 299.3 kB/s eta 0:00:08
     ------------------------------- ------- 9.7/11.9 MB 299.3 kB/s eta 0:00:08
     ------------------------------- ------- 9.7/11.9 MB 299.3 kB/s eta 0:00:08
     ------------------------------- ------ 10.0/11.9 MB 303.8 kB/s eta 0:00:07
     ------------------------------- ------ 10.0/11.9 MB 303.8 kB/s eta 0:00:07
     -------------------------------- ----- 10.2/11.9 MB 307.2 kB/s eta 0:00:06
     -------------------------------- ----- 10.2/11.9 MB 307.2 kB/s eta 0:00:06
     -------------------------------- ----- 10.2/11.9 MB 307.2 kB/s eta 0:00:06
     -------------------------------- ----- 10.2/11.9 MB 307.2 kB/s eta 0:00:06
     -------------------------------- ----- 10.2/11.9 MB 307.2 kB/s eta 0:00:06
     -------------------------------- ----- 10.2/11.9 MB 307.2 kB/s eta 0:00:06
     --------------------------------- ---- 10.5/11.9 MB 306.3 kB/s eta 0:00:05
     --------------------------------- ---- 10.5/11.9 MB 306.3 kB/s eta 0:00:05
     --------------------------------- ---- 10.5/11.9 MB 306.3 kB/s eta 0:00:05
     --------------------------------- ---- 10.5/11.9 MB 306.3 kB/s eta 0:00:05
     ---------------------------------- --- 10.7/11.9 MB 332.4 kB/s eta 0:00:04
     ---------------------------------- --- 10.7/11.9 MB 332.4 kB/s eta 0:00:04
     ----------------------------------- -- 11.0/11.9 MB 335.4 kB/s eta 0:00:03
     ----------------------------------- -- 11.0/11.9 MB 335.4 kB/s eta 0:00:03
     ------------------------------------ - 11.3/11.9 MB 339.5 kB/s eta 0:00:02
     ------------------------------------ - 11.3/11.9 MB 339.5 kB/s eta 0:00:02
     ------------------------------------ - 11.5/11.9 MB 343.9 kB/s eta 0:00:01
     ------------------------------------ - 11.5/11.9 MB 343.9 kB/s eta 0:00:01
     -------------------------------------  11.8/11.9 MB 347.5 kB/s eta 0:00:01
     -------------------------------------- 11.9/11.9 MB 348.9 kB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: mysql.connector
  Building wheel for mysql.connector (setup.py): started
  Building wheel for mysql.connector (setup.py): finished with status 'done'
  Created wheel for mysql.connector: filename=mysql_connector-2.2.9-cp313-cp313-win_amd64.whl size=247959 sha256=f5ed6b74d72677bb3b917767d96b0bfebf865d1141987de80fe1f189dbdccbc7
  Stored in directory: c:\users\mayank\appdata\local\pip\cache\wheels\4e\c1\23\9423c444a75266a05275c80ebf5c6efe2368388e976b690a0f
Successfully built mysql.connector
Installing collected packages: mysql.connector
Successfully installed mysql.connector-2.2.9

WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Mayank\Downloads\python.Mayank\Lib\site-packages)
  DEPRECATION: Building 'mysql.connector' using the legacy setup.py bdist_wheel mechanism, which will be removed in a future version. pip 25.3 will enforce this behaviour change. A possible replacement is to use the standardized build interface by setting the `--use-pep517` option, (possibly combined with `--no-build-isolation`), or adding a `pyproject.toml` file to the source tree of 'mysql.connector'. Discussion can be found at https://github.com/pypa/pip/issues/6334
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Mayank\Downloads\python.Mayank\Lib\site-packages)
WARNING: Ignoring invalid distribution ~atplotlib (C:\Users\Mayank\Downloads\python.Mayank\Lib\site-packages)

In [4]:
import mysql.connector

In [11]:
conn= mysql.connector.connect(host="localhost",user="root",password="",database="world")

In [14]:
df = pd.read_sql_query("select * from city where CountryCode like 'USA' ",conn)
df

C:\Users\Mayank\AppData\Local\Temp\ipykernel_7796\3416930879.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("select * from city where CountryCode like 'USA' ",conn)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]